const canvas=document.getElementById('gameCanvas'),ctx=canvas.getContext('2d');
const ui=Object.fromEntries(['startScreen','gameOverScreen','playButton','retryButton','homeButton','finalScore','bestScore','earnedCoins','earnedXp','coinLabel','levelLabel','xpLabel','xpFill','missionList','missionCount','toast','resetProgress','skinPicker','scenePicker','selectedSkinLabel','selectedSceneLabel'].map(id=>[id,document.getElementById(id)]));
const sounds={jump:document.getElementById('jumpSound'),score:document.getElementById('scoreSound'),over:document.getElementById('gameOverSound')};
const skins=[
 {id:'classic',name:'Byrd Clássico',src:'bird.png',scale:1},
 {id:'parrot',name:'Papagaio',src:'assets/skins/papagaio.png',scale:1.16},
 {id:'bat',name:'Morcego',src:'assets/skins/morcego.png',scale:1.18},
 {id:'cat',name:'Super-Gato',src:'assets/skins/super-gato.png',scale:1.12},
 {id:'dog',name:'Super-Cão',src:'assets/skins/super-cao.png',scale:1.15},
 {id:'bee',name:'Abelhinha',src:'assets/skins/abelhinha.png',scale:1.16}
];
const scenes=[
 {id:'dawn',name:'Amanhecer',sky:['#0e496b','#2a7790','#eab86f'],pipe:['#07564d','#33c095','#043e40'],ground:'#071b2a',accent:'#1f8a82'},
 {id:'day',name:'Dia Tropical',sky:['#2697d4','#66cdeb','#d8f6fa'],pipe:['#166d36','#65d75e','#164a2d'],ground:'#174832',accent:'#66d866'},
 {id:'night',name:'Noite Lunar',sky:['#050b1d','#102b51','#24466b'],pipe:['#34286e','#7969c7','#211a4b'],ground:'#080c1d',accent:'#8b82d8'},
 {id:'aurora',name:'Aurora Mágica',sky:['#07142d','#15576d','#7d568f'],pipe:['#15526a','#48cfb4','#28345f'],ground:'#07172a',accent:'#72ead2'}
];
const skinImages=Object.fromEntries(skins.map(s=>{const img=new Image();img.src=s.src;return[s.id,img]}));
const bgImg=new Image();bgImg.src='background.png';
const STORAGE_KEY='flappyByrdProgressV2',defaultSave={coins:0,xp:0,best:0,totalPipes:0,totalFlights:0,missions:{},skin:'classic',scene:'dawn'};
let save=loadSave(),state='menu',score=0,runCoins=0,lastTime=0,spawnTimer=0,worldTime=0,flash=0,pipes=[],particles=[],stars=[];
const bird={x:92,y:320,w:46,h:36,vy:0,rotation:0};
const missions=[
 {id:'first5',icon:'➤',title:'Aquecimento',text:'Passe por 5 obstáculos',goal:5,reward:25,value:()=>save.totalPipes},
 {id:'score10',icon:'★',title:'Voo de elite',text:'Faça 10 pontos em um voo',goal:10,reward:45,value:()=>Math.min(save.best,10)},
 {id:'fly3',icon:'↻',title:'Persistência',text:'Complete 3 voos',goal:3,reward:30,value:()=>save.totalFlights}
];
function loadSave(){try{const loaded={...defaultSave,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')};if(!skins.some(s=>s.id===loaded.skin))loaded.skin='classic';if(!scenes.some(s=>s.id===loaded.scene))loaded.scene='dawn';return loaded}catch{return{...defaultSave}}}
function persist(){localStorage.setItem(STORAGE_KEY,JSON.stringify(save));updateMetaUI()}
function levelInfo(){return{level:Math.floor(save.xp/100)+1,current:save.xp%100}}
function updateMetaUI(){const l=levelInfo();ui.coinLabel.textContent=save.coins;ui.levelLabel.textContent='NÍVEL '+l.level;ui.xpLabel.textContent=l.current+'/100 XP';ui.xpFill.style.width=l.current+'%';renderMissions()}
function renderMissions(){let done=0;ui.missionList.innerHTML=missions.map(m=>{const val=Math.min(m.value(),m.goal),complete=!!save.missions[m.id];if(complete)done++;return '<article class="mission '+(complete?'done':'')+'"><span class="mission-reward">'+(complete?'✓ RESGATADO':'+'+m.reward+' ◆')+'</span><div class="mission-top"><span class="mission-icon">'+m.icon+'</span><div><h3>'+m.title+'</h3><small>'+m.text+' · '+val+'/'+m.goal+'</small></div></div><div class="mission-progress"><i style="width:'+(val/m.goal*100)+'%"></i></div></article>'}).join('');ui.missionCount.textContent=done+'/3 concluídas'}
function checkMissions(){for(const m of missions)if(!save.missions[m.id]&&m.value()>=m.goal){save.missions[m.id]=true;save.coins+=m.reward;showToast('MISSÃO CONCLUÍDA · +'+m.reward+' ◆')}}
function showToast(text){ui.toast.textContent=text;ui.toast.classList.remove('hidden');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>ui.toast.classList.add('hidden'),2200)}
function renderCustomizer(){ui.skinPicker.innerHTML=skins.map(s=>'<button class="skin-option '+(save.skin===s.id?'active':'')+'" data-skin="'+s.id+'" aria-label="Selecionar '+s.name+'" aria-pressed="'+(save.skin===s.id)+'"><img src="'+s.src+'" alt=""></button>').join('');ui.scenePicker.innerHTML=scenes.map(s=>'<button class="scene-option '+(save.scene===s.id?'active':'')+'" data-scene="'+s.id+'" aria-pressed="'+(save.scene===s.id)+'"><span>'+s.name+'</span></button>').join('');ui.selectedSkinLabel.textContent=skins.find(s=>s.id===save.skin).name.toUpperCase();ui.selectedSceneLabel.textContent=scenes.find(s=>s.id===save.scene).name.toUpperCase()}
function selectSkin(id){if(state!=='menu'||!skins.some(s=>s.id===id))return;save.skin=id;persist();renderCustomizer()}
function selectScene(id){if(state!=='menu'||!scenes.some(s=>s.id===id))return;save.scene=id;createStars();persist();renderCustomizer()}
function playSound(sound){sound.currentTime=0;sound.play().catch(()=>{})}
function resizeCanvas(){const dpr=Math.min(devicePixelRatio||1,2),rect=canvas.getBoundingClientRect();canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);canvas.logicalWidth=rect.width;canvas.logicalHeight=rect.height;createStars()}
function createStars(){stars=Array.from({length:38},()=>({x:Math.random()*canvas.logicalWidth,y:Math.random()*canvas.logicalHeight*.78,r:Math.random()*1.4+.3,a:Math.random()*.65+.15}))}
function resetRun(){score=0;runCoins=0;pipes=[];particles=[];bird.y=canvas.logicalHeight*.48;bird.vy=0;bird.rotation=0;spawnTimer=900;flash=0}
function startGame(){resetRun();state='playing';ui.startScreen.classList.add('hidden');ui.gameOverScreen.classList.add('hidden')}
function goHome(){state='menu';resetRun();ui.gameOverScreen.classList.add('hidden');ui.startScreen.classList.remove('hidden')}
function flap(){if(state==='menu'||state==='over'){startGame();return}bird.vy=-430;playSound(sounds.jump);for(let i=0;i<7;i++)particles.push({x:bird.x,y:bird.y+bird.h/2,vx:-70-Math.random()*80,vy:(Math.random()-.5)*80,life:1})}
function spawnPipe(){const h=canvas.logicalHeight,gap=Math.max(142,178-score*1.3),margin=82,top=margin+Math.random()*(h-gap-margin*2);pipes.push({x:canvas.logicalWidth+35,top,gap,w:58,passed:false})}
function endGame(){if(state!=='playing')return;state='over';save.totalFlights++;save.best=Math.max(save.best,score);const xp=8+score*4;runCoins=Math.floor(score/2);save.xp+=xp;save.coins+=runCoins;checkMissions();persist();ui.finalScore.textContent=score;ui.bestScore.textContent=save.best;ui.earnedCoins.textContent=runCoins;ui.earnedXp.textContent=xp;ui.gameOverScreen.classList.remove('hidden');playSound(sounds.over)}
function update(dt){worldTime+=dt;if(state!=='playing')return;bird.vy+=1150*dt;bird.y+=bird.vy*dt;bird.rotation=Math.max(-.35,Math.min(1.05,bird.vy/650));spawnTimer-=dt*1000;if(spawnTimer<=0){spawnPipe();spawnTimer=Math.max(1050,1450-score*12)}const speed=Math.min(250,150+score*3.2);for(const p of pipes){p.x-=speed*dt;if(!p.passed&&p.x+p.w<bird.x){p.passed=true;score++;save.totalPipes++;playSound(sounds.score);flash=1;checkMissions();persist()}const bx=bird.x+7,by=bird.y+5,bw=bird.w-14,bh=bird.h-10;if(bx<p.x+p.w&&bx+bw>p.x&&(by<p.top||by+bh>p.top+p.gap))endGame()}pipes=pipes.filter(p=>p.x+p.w>-10);if(bird.y<-30||bird.y+bird.h>canvas.logicalHeight-28)endGame();for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt*1.8}particles=particles.filter(p=>p.life>0);flash=Math.max(0,flash-dt*3)}
function drawBackground(w,h){const scene=scenes.find(s=>s.id===save.scene)||scenes[0],g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,scene.sky[0]);g.addColorStop(.56,scene.sky[1]);g.addColorStop(1,scene.sky[2]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.globalAlpha=save.scene==='dawn'?.2:.08;if(bgImg.complete)ctx.drawImage(bgImg,0,0,w,h);ctx.globalAlpha=1;if(save.scene==='night'||save.scene==='aurora')for(const s of stars){ctx.globalAlpha=s.a*(.7+.3*Math.sin(worldTime*2+s.x));ctx.fillStyle='#dfffff';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()}ctx.globalAlpha=1;if(save.scene==='night'){ctx.fillStyle='#eef7dd';ctx.beginPath();ctx.arc(w*.77,h*.18,27,0,7);ctx.fill();ctx.fillStyle=scene.sky[0];ctx.beginPath();ctx.arc(w*.79,h*.165,24,0,7);ctx.fill()}else{const sun=ctx.createRadialGradient(w*.76,h*.2,2,w*.76,h*.2,62);sun.addColorStop(0,save.scene==='aurora'?'rgba(115,255,203,.55)':'rgba(255,229,145,.7)');sun.addColorStop(1,'rgba(255,208,98,0)');ctx.fillStyle=sun;ctx.fillRect(0,0,w,h)}if(save.scene==='aurora'){ctx.save();ctx.globalAlpha=.2;ctx.strokeStyle='#75ffd0';ctx.lineWidth=28;ctx.beginPath();ctx.moveTo(-30,h*.22);ctx.bezierCurveTo(w*.25,h*.05,w*.55,h*.35,w+30,h*.12);ctx.stroke();ctx.restore()}drawCloud(w*.15+(worldTime*8)%w,h*.2,1);drawCloud(w*.8-(worldTime*5)%w,h*.33,.7);ctx.fillStyle='rgba(5,27,41,.3)';for(let i=0;i<9;i++){const x=i*w/8-(worldTime*12%(w/8));ctx.beginPath();ctx.moveTo(x,h);ctx.lineTo(x+65,h*.62);ctx.lineTo(x+130,h);ctx.fill()}ctx.fillStyle=scene.ground;ctx.fillRect(0,h-28,w,28);ctx.fillStyle=scene.accent;ctx.fillRect(0,h-28,w,4)}
function drawCloud(x,y,s){ctx.save();ctx.globalAlpha=.17;ctx.fillStyle='#dffaff';ctx.beginPath();ctx.ellipse(x,y,70*s,20*s,0,0,7);ctx.ellipse(x+35*s,y-14*s,42*s,28*s,0,0,7);ctx.ellipse(x-30*s,y-8*s,34*s,24*s,0,0,7);ctx.fill();ctx.restore()}
function drawPipe(p,h){const scene=scenes.find(s=>s.id===save.scene)||scenes[0],grad=ctx.createLinearGradient(p.x,0,p.x+p.w,0);grad.addColorStop(0,scene.pipe[0]);grad.addColorStop(.4,scene.pipe[1]);grad.addColorStop(1,scene.pipe[2]);ctx.fillStyle=grad;ctx.strokeStyle='rgba(190,255,235,.5)';ctx.lineWidth=2;const cap=13;ctx.fillRect(p.x,0,p.w,p.top-cap);ctx.strokeRect(p.x,0,p.w,p.top-cap);ctx.fillRect(p.x-6,p.top-cap,p.w+12,cap);ctx.strokeRect(p.x-6,p.top-cap,p.w+12,cap);const bottom=p.top+p.gap;ctx.fillRect(p.x,bottom+cap,p.w,h-bottom-cap);ctx.strokeRect(p.x,bottom+cap,p.w,h-bottom-cap);ctx.fillRect(p.x-6,bottom,p.w+12,cap);ctx.strokeRect(p.x-6,bottom,p.w+12,cap);ctx.fillStyle='rgba(255,255,255,.22)';ctx.fillRect(p.x+9,0,4,p.top-cap);ctx.fillRect(p.x+9,bottom+cap,4,h-bottom)}
function drawBird(){const skin=skins.find(s=>s.id===save.skin)||skins[0],img=skinImages[skin.id],dw=bird.w*skin.scale,dh=bird.h*skin.scale;ctx.save();ctx.translate(bird.x+bird.w/2,bird.y+bird.h/2);ctx.rotate(bird.rotation);ctx.shadowColor=save.scene==='night'?'rgba(145,130,255,.55)':'rgba(255,207,62,.5)';ctx.shadowBlur=15;if(img.complete&&img.naturalWidth)ctx.drawImage(img,-dw/2,-dh/2,dw,dh);else{ctx.fillStyle='#ffd447';ctx.beginPath();ctx.ellipse(0,0,22,16,0,0,7);ctx.fill()}ctx.restore()}
function drawHUD(w){if(state!=='playing')return;ctx.textAlign='center';ctx.shadowColor='rgba(0,0,0,.4)';ctx.shadowBlur=8;ctx.fillStyle='#fff';ctx.font='800 54px Barlow Condensed, sans-serif';ctx.fillText(score,w/2,70);ctx.shadowBlur=0;ctx.fillStyle='rgba(4,22,37,.6)';ctx.fillRect(w/2-39,80,78,20);ctx.fillStyle='#9ed1dc';ctx.font='700 9px Inter';ctx.fillText('PONTOS',w/2,94);if(score<3){ctx.fillStyle='rgba(255,255,255,.7)';ctx.font='600 10px Inter';ctx.fillText('TOQUE PARA VOAR',w/2,canvas.logicalHeight-52)}}
function render(){const w=canvas.logicalWidth,h=canvas.logicalHeight;ctx.clearRect(0,0,w,h);drawBackground(w,h);pipes.forEach(p=>drawPipe(p,h));particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle='#ffe16f';ctx.fillRect(p.x,p.y,5,3)});ctx.globalAlpha=1;drawBird();drawHUD(w);if(flash>0){ctx.globalAlpha=flash*.14;ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);ctx.globalAlpha=1}}
function loop(t){const dt=Math.min((t-lastTime)/1000||0,.033);lastTime=t;update(dt);render();requestAnimationFrame(loop)}
function handleAction(e){if(e.type==='keydown'&&!['Space','ArrowUp','KeyW'].includes(e.code))return;e.preventDefault();flap()}
ui.playButton.addEventListener('click',startGame);ui.retryButton.addEventListener('click',startGame);ui.homeButton.addEventListener('click',goHome);canvas.addEventListener('pointerdown',handleAction);window.addEventListener('keydown',handleAction);window.addEventListener('resize',resizeCanvas);
ui.skinPicker.addEventListener('click',e=>{const button=e.target.closest('[data-skin]');if(button)selectSkin(button.dataset.skin)});ui.scenePicker.addEventListener('click',e=>{const button=e.target.closest('[data-scene]');if(button)selectScene(button.dataset.scene)});
ui.resetProgress.addEventListener('click',()=>{if(confirm('Reiniciar moedas, recorde, nível, missões e personalização?')){save={...defaultSave,missions:{}};persist();renderCustomizer();showToast('PROGRESSO REINICIADO')}});
resizeCanvas();updateMetaUI();renderCustomizer();requestAnimationFrame(loop);
